### ISSUE TITLE
Create Milestones

### ISSUE THREAD

**Issue by thedigitalmenagerie** [thedigitalmenagerie/mesi#6]
## Feature Summary

As an architect, create the milestones  that follow the planning milestone for each step of the process and its relevant due date. 

## Acceptance Criteria

Must include the description and cover each step in the application development process for MESI.

## Technical Requirements

- [x] Database creation with Sample Data with due date
- [x] Back-end CRUD with due date
- [x] Front-end CRUD with due date
